export const lang = {
    book_list: '书单',
    account: '帐户',
    login: '登录',
    bookmark: '书架',
    ciweicat_new_book_list: '最近新书',
    ciweicat_up_book_list: '最近更新',
    account_ciweimao: '钱包君',
    author: '作者',
    update: 'Update',
    newest_chapter: 'Latest chapter',
    website: '網站',
    category: '作品分类',
    tags: 'Tags',
    introduce: '作品简介',
    bookmarked: '完毕',
    view_book_list: '书单',
    view_review: '书评',
    review: '书评',
    get_token_ciweimao: 'Get token Ciweimao',
    login_nhimmeo: 'Login Nhimmeo',
    default_account_by_admin: 'default',
    story: 'Novel',
    review_of_book: '书评: ',
    please_not_empty: 'Please not empty!',
    saved_cookie: 'Saved cookie account & login token',
    removed_cookie: 'Removed cookie account & login token',
    search: '搜索',
    search_result: 'Search result',
    catalog: '章节目录',
    // ETC
};
